config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  resources :pictures do
    collection do
      post :confirm
    end
  end

  resources :users, only: [:new, :create, :show, :destroy] do
    collection do
      get :favorite
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  mount_uploader :image, ImageUploader

  validates :image, presence: true
  validates :content,    length: { maximum: 150 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures,  dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture

  before_validation {email.downcase!}
  validates :name,  presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255},
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: {minimum: 6}

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end
# 変数に入れてる？
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show,:edit,:update,:destroy]
  before_action :require_logged_in!, only: [:new, :edit, :show, :destroy]

  def index
    @page = params[:page].to_i
    @page = 0 if @page == nil
    @page_num = 6
    @record_count = Picture.where("id > 0").count
    @results = Picture.where("id > 0").order("id DESC")
                       .offset(@page * @page_num).limit(@page_num)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    binding.pry
    if @picture.save
      #ContactMailer.picture_create_mail(@picture).deliver
      redirect_to pictures_path, notice: "create"
    else
      render 'new'
    end
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render 'new' if @picture.invalid?
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
    @user = User.find_by(id: @picture.user_id)
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice:"update"
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"delete"
  end

  private
  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'メールアドレス又はパスワードが違います'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def favorite
    @user = current_user
    @favorite_pictures = @user.favorite_pictures
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id:session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def require_logged_in!
    redirect_to new_session_path unless logged_in?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CAMPUS</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <h1>CAMPUS</h1>
    </header>

    <nav class="container">
      <ul>
        <div class="header_link row">
        <% if logged_in? %>
          <li class="col-lg-3 col-sm-6 col-xs-12"><%= link_to "Profile", user_path(current_user.id) %></li>
          <li class="col-lg-3 col-sm-6 col-xs-12"><%= link_to 'Create', new_picture_path %></li>
          <li class="col-lg-3 col-sm-6 col-xs-12"><%= link_to 'List', pictures_path %></li>
          <li class="col-lg-3 col-sm-6 col-xs-12"><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
        <% else %>
          <li class="col-sm-6 col-xs-12"><%= link_to "Sign up", new_user_path %></li>
          <li class="col-sm-6 col-xs-12"><%= link_to "Login", new_session_path %></li>
        <% end %>
      </div>
      </ul>
    </nav>

    <article>
    <%= yield %>
    </article>

    <footer>
      <address>CAMPUS</address>
    </footer>

  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |f| %>

  <% if @picture.errors.any? %>
    <div id="picture_error_explanation">
      <p><%= @picture.errors.count %>件のエラーがあります。</p>
      <% @picture.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>
<div class="form_content">
<div class="form_image">
  <%= f.label :image %><br>
  <%= f.file_field :image %>
</div>
<div class="form_text">
  <%= f.text_area :content,  placeholder: "本文を入力してください" %>
</div>

  <%= f.submit 'create', class: "btn btn-default" %>

<% end %>
</div>

app/views/pictures/confirm.html.erb
<div class="confirm_title">
  <h1>confirm</h1>
</div>

<div class="confirm_content">
  <%= form_with(model: @picture, url: pictures_path, local: true) do |f| %>
    <%= f.hidden_field :image_cache %>
    <%= f.hidden_field :content %>
    <div class="confirm_image">
      <%= image_tag(@picture.image.url) %>
    </div>
    <div class="confirm_text">
      <%= @picture.content %>
    </div>
    <%= f.submit 'create', class: "btn btn-default" %>
  <% end %>

  <%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |f| %>
    <%= f.hidden_field :image_cache %>
    <%= f.hidden_field :content %>
    <%= f.submit 'back', name: 'back', class: "btn btn-sm" %>
  <% end %>
</div>

app/views/pictures/edit.html.erb
<h1>edit</h1>

<%= render 'form' %>

app/views/pictures/index.html.erb
<div class="list_content">
  <div class="container">
    <div class="row">
      <% @results.each do |result| %>
        <div class="list_image col-lg-4 col-sm-6 col-xs-12">
  	       <%= link_to image_tag(result.image), picture_path(result.id) %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="list_page">
    <% if @page > 0 then %>
      <a href="/pictures?page=<%=@page - 1 %>" class="btn btn-default"><%=@page %></a>
    <% end %>
    <p><%=(@page + 1)%></p>
    <% if @record_count > (@page + 1) * @page_num %>
      <a href="/pictures?page=<%=@page + 1 %>" class="btn btn-default"><%=@page + 2 %></a>
    <% end %>
  </div>
</div>

app/views/pictures/new.html.erb
<div class="create_title">
  <h1>Create</h1>
</div>

<%= render 'form' %>

app/views/pictures/show.html.erb
<div class="show_content">
  <div class="show_title">
    <h1>Show</h1>
  </div>

  <div class="show_image">
    <%= image_tag @picture.image %>
  </div>

  <div class="show_text">
    <%= @picture.content %>
  </div>

  <div class="show_name">
    <p>ユーザー名: <%= @user.name %></p>
  </div>

  <div class="show_btn">
    <% if @picture.user_id == current_user.id %>
      <%= link_to '編集', edit_picture_path(id: @picture.id), class:'btn btn-primary' %>
      <%= link_to '削除', picture_path(id: @picture.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <% if @favorite.present? %>
        <%= link_to 'お気に入り解除', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'お気に入り', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/favorite.html.erb
<div class="favorite_content">
  <div class="favorite_title">
    <h1>Favorite</h1>
  </div>

  <div class="favorite_image">
    <% @favorite_pictures.reverse.each do |favorites| %>
      <p><%= link_to image_tag(favorites.image), picture_path(favorites.id) %></p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="signup_title">
  <h1>CAMPUSへようこそ！</h1>
</div>

<% if @user.errors.any? %>
  <div id="user_error_explanation">
    <p><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</p>
    <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>
<% end %>

<div class="container">
  <div class="low">
    <div class="signup_content col-xs-12 col-sm-6 col-md-offset-1">
      <p>
        CAMPUSは画像投稿アプリです。<br>
        みなさんの画像を持ち寄って遊んでみてください。
      </p>
    </div>
    <div class="signup_form col-xs-12 col-sm-4 col-md-offset-1">
      <h2>Sign up</h2>
      <%= form_with(model: @user, local: true) do |f| %>
        <%= f.label :name %><br>
        <%= f.text_field :name %><br>

        <%= f.label :email %><br>
        <%= f.email_field :email %><br>

        <%= f.label :password %><br>
        <%= f.password_field :password %><br>

        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %><br>

        <%= f.submit "Create my account" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="mypage_content">
  <h1>Profile</h1>
  <div class="mypage_name">
    <p>
      名前<br>
      <%= @user.name %>
    </p>
  </div>
  <div class="mypage_email">
    <p>
      メールアドレス<br>
      <%= @user.email %>
    </p>
  </div>
  <%= link_to 'お気に入り一覧', favorite_users_path, class: "btn btn-default btn-lg" %>
</div>

app/views/users/test.html.erb
<h1>これはテストです</h1>
さらにてすと
さらにさらにてすと
ブランツ名変更